[package]
name = "mock-ellipticoin"
version = "0.1.1"
authors = ["Mason Fischer <mason@kissr.co>"]
description = "A framework for testing Ellipticoin smart contracts"
license = "MIT"

[dependencies]
wasm-rpc = "0.2.12"
wasm-rpc-macros = "0.2.12"
ellipticoin = "0.1.4"
